/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HikmetTerzioglu_481_hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testFound2Numbers() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        assertTrue(App.Add2NumbersAndUpdateIndex(array,4,3,2));
    }
    @Test
    public void testNotFoundOneOfNumbers() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      assertFalse(App.Add2NumbersAndUpdateIndex(array, 10,2,3));
    }
    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      assertFalse(App.Add2NumbersAndUpdateIndex(array,1,2,4));
    }
    @Test
    public void testInvalidIndex() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7,8));
      assertFalse(App.Add2NumbersAndUpdateIndex(array, 10,2,10));
    }
    @Test
    public void testNotFound2Numbers() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      assertFalse(App.Add2NumbersAndUpdateIndex(array, 10,20,3));
    }
}
