/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HikmetTerzioglu_481_hw1;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }


    //The method that finds the two numbers given in the parameter in the ArrayList and updates the number given the index.

    //If it does not find any numbers in the ArrayList, it returns false.

    //If it is updated, it will return true.
    //if the index is not in the range of the arraylist length, it returns false.

    public static boolean Add2NumbersAndUpdateIndex(ArrayList<Integer> array,int first,int second,int index){

        int count=0;
        int index1=0;
        int index2=0;
        int update=0;
        if (array == null) return false;

        if(index<0||index>array.size()) return false;

        for(int i=0;i<array.size();i++){
            if(first==array.get(i)){
                count++;
                index1=i;
            }else if(second==array.get(i)){
                count++;
                index2=i;
            }
        }
        if(count==2){
            update=array.get(index1)+array.get(index2);
            array.set(index, update);
            return true;
        }else if(count<2){
            return false;
        }

        return true;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
